name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - book_catalog/**
      - inventory_management/**
      - scripts/terraform/**
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the version to tag the Docker image'
        required: true
        default: 'latest'

jobs:
  # Job 1: Terraform Infrastructure Deployment
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: "part4 2/scripts/terraform"

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="app_name=${{ secrets.APP_NAME }}" -var="kubernetes_version=${{ secrets.KUBERNETES_VERSION }}" -var="subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" -var="client_id=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" -var="client_secret=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" -var="tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
        working-directory: "part4 2/scripts/terraform"

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="app_name=${{ secrets.APP_NAME }}" -var="kubernetes_version=${{ secrets.KUBERNETES_VERSION }}" -var="subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" -var="client_id=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" -var="client_secret=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" -var="tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
        working-directory: "part4 2/scripts/terraform"

      # Capture Terraform outputs and set them as environment variables
      - name: Get Terraform Outputs
        id: terraform_outputs
        run: |
          acr_login_url=$(terraform output -raw container_registry | tr -d '\r\n')
          echo "acr_login_url=$acr_login_url" >> $GITHUB_ENV

          acr_username=$(terraform output -raw registry_username | tr -d '\r\n')
          echo "acr_username=$acr_username" >> $GITHUB_ENV

          acr_password=$(terraform output -raw registry_password | tr -d '\r\n')
          echo "acr_password=$acr_password" >> $GITHUB_ENV

          aks_kubeconfig=$(terraform output -raw kube_config | tr -d '\r\n')
          echo "aks_kubeconfig=$aks_kubeconfig" >> $GITHUB_ENV
        working-directory: "part4 2/scripts/terraform"

      # Set up GitHub CLI
      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2

      # Authenticate GitHub CLI
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.SECRETS_MODIFY_TOKEN }}" | gh auth login --with-token

      # Create or update GitHub secrets
      - name: Create GitHub Secrets
        run: |
          gh secret set CONTAINER_REGISTRY -b "${{ env.acr_login_url }}"
          gh secret set REGISTRY_UN -b "${{ env.acr_username }}"
          gh secret set REGISTRY_PW -b "${{ env.acr_password }}"
          gh secret set KUBE_CONFIG -b "${{ env.aks_kubeconfig }}"

  # Job 2: Deploy Book Catalog Microservice
  deploy_book_catalog:
    name: Deploy book_catalog
    runs-on: ubuntu-latest
    needs: terraform  # Ensure this job waits for Terraform to complete

    env:
      VERSION: ${{ github.event.inputs.version }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      NAME: book_catalog
      DIRECTORY: book_catalog

    steps:
      - uses: actions/checkout@v3

      # Set executable permissions for all scripts
      - name: Set permissions for build, push, deploy scripts
        run: |
          chmod +x "part4 2/scripts/build-image.sh"
          chmod +x "part4 2/scripts/push-image.sh"
          chmod +x "part4 2/scripts/deploy.sh"

      # Log in to the container registry
      - name: Log in to container registry
        run: echo "${{ secrets.REGISTRY_PW }}" | docker login ${{ secrets.CONTAINER_REGISTRY }} -u "${{ secrets.REGISTRY_UN }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: "part4 2/scripts/build-image.sh ${{ env.VERSION }}"

      # Push the Docker image to the container registry
      - name: Publish Docker image
        run: "part4 2/scripts/push-image.sh ${{ env.VERSION }}"

  # Job 3: Deploy Inventory Management Microservice
  deploy_inventory_management:
    name: Deploy inventory_management
    runs-on: ubuntu-latest
    needs: terraform

    env:
      VERSION: ${{ github.event.inputs.version }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      NAME: inventory_management
      DIRECTORY: inventory_management

    steps:
      - uses: actions/checkout@v3

      # Set executable permissions for all scripts
      - name: Set permissions for build, push, deploy scripts
        run: |
          chmod +x "part4 2/scripts/build-image.sh"
          chmod +x "part4 2/scripts/push-image.sh"
          chmod +x "part4 2/scripts/deploy.sh"

      # Log in to the container registry
      - name: Log in to container registry
        run: echo "${{ secrets.REGISTRY_PW }}" | docker login ${{ secrets.CONTAINER_REGISTRY }} -u "${{ secrets.REGISTRY_UN }}" --password-stdin

      # Build the Docker image
      - name: Build Docker image
        run: "part4 2/scripts/build-image.sh ${{ env.VERSION }}"

      # Push the Docker image to the container registry
      - name: Publish Docker image
