name: CI/CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - book_catalog/**
      - inventory_management/**
      - scripts/terraform/**
  workflow_dispatch:  # Allows triggering manually
    inputs:
      version:
        description: 'Enter the version to tag the Docker image'
        required: true
        default: 'latest'

jobs:
  # Job 1: Terraform Infrastructure Deployment
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    outputs:
      acr_login_url: ${{ steps.get_outputs.outputs.acr_login_url }}
      acr_username: ${{ steps.get_outputs.outputs.acr_username }}
      acr_password: ${{ steps.get_outputs.outputs.acr_password }}
      aks_kubeconfig: ${{ steps.get_outputs.outputs.aks_kubeconfig }}

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: "part4 2/scripts/terraform"

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -var="app_name=${{ secrets.APP_NAME }}" -var="kubernetes_version=${{ secrets.KUBERNETES_VERSION }}" -var="subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" -var="client_id=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" -var="client_secret=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" -var="tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
        working-directory: "part4 2/scripts/terraform"

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="app_name=${{ secrets.APP_NAME }}" -var="kubernetes_version=${{ secrets.KUBERNETES_VERSION }}" -var="subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" -var="client_id=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" -var="client_secret=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" -var="tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"
        working-directory: "part4 2/scripts/terraform"

      # Capture Terraform outputs and set them as environment variables
      - name: Get Terraform Outputs
        id: get_outputs
        run: |
          echo "ACR_LOGIN_URL=$(terraform output -raw container_registry | tr -d '\r\n')" >> $GITHUB_ENV
          echo "ACR_USERNAME=$(terraform output -raw registry_username | tr -d '\r\n')" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$(terraform output -raw registry_password | tr -d '\r\n')" >> $GITHUB_ENV
          echo "AKS_KUBECONFIG=$(terraform output -raw kube_config | tr -d '\r\n')" >> $GITHUB_ENV
        working-directory: "part4 2/scripts/terraform"

  # Job 2: Deploy Book Catalog Microservice
  deploy_book_catalog:
    name: Deploy book_catalog
    runs-on: ubuntu-latest
    needs: terraform  # Ensure this job waits for Terraform to complete

    env:
      VERSION: ${{ github.event.inputs.version }}  # Use version input provided during manual dispatch
      CONTAINER_REGISTRY: ${{ env.ACR_LOGIN_URL }}
      REGISTRY_UN: ${{ env.ACR_USERNAME }}
      REGISTRY_PW: ${{ env.ACR_PASSWORD }}
      KUBE_CONFIG: ${{ env.AKS_KUBECONFIG }}
      NAME: book_catalog
      DIRECTORY: book_catalog

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Set executable permissions for all scripts
      - name: Set permissions for build, push, deploy scripts
        run: |
          chmod +x part4\ 2/scripts/build-image.sh
          chmod +x part4\ 2/scripts/push-image.sh
          chmod +x part4\ 2/scripts/deploy.sh

      # Build the Docker image
      - name: Build Docker image
        run: part4\ 2/scripts/build-image.sh ${{ env.VERSION }}  # Pass the version to the script

      # Push the Docker image to the container registry
      - name: Publish Docker image
        run: part4\ 2/scripts/push-image.sh ${{ env.VERSION }}  # Pass the version to the script

  # Job 3: Deploy Inventory Management Microservice
  deploy_inventory_management:
    name: Deploy inventory_management
    runs-on: ubuntu-latest
    needs: terraform  # Ensure this job waits for Terraform to complete

    env:
      VERSION: ${{ github.event.inputs.version }}  # Use version input provided during manual dispatch
      CONTAINER_REGISTRY: ${{ env.ACR_LOGIN_URL }}
      REGISTRY_UN: ${{ env.ACR_USERNAME }}
      REGISTRY_PW: ${{ env.ACR_PASSWORD }}
      KUBE_CONFIG: ${{ env.AKS_KUBECONFIG }}
      NAME: inventory_management
      DIRECTORY: inventory_management

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Set executable permissions for all scripts
      - name: Set permissions for build, push, deploy scripts
        run: |
          chmod +x part4\ 2/scripts/build-image.sh
          chmod +x part4\ 2/scripts/push-image.sh
          chmod +x part4\ 2/scripts/deploy.sh

      # Build the Docker image
      - name: Build Docker image
        run: part4\ 2/scripts/build-image.sh ${{ env.VERSION }}  # Pass the version to the script

      # Push the Docker image to the container registry
      - name: Publish Docker image
        run: part4\ 2/scripts/push-image.sh ${{ env.VERSION }}  # Pass the version to the script

      # Install Kubectl and deploy to Kubernetes
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ env.KUBE_CONFIG }}
          kubectl-version: v1.24.2

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: part4\ 2/scripts/kubernetes/deploy.sh
